server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name data-science-efrei.remipetit.fr;

    include /config/nginx/ssl.conf;
    client_max_body_size 0;

    # FastAPI — /api/* → fastapi:8000/*
    location /api/ {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app fastapi_efrei_data_science;
        set $upstream_port 8000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port/;
    }

    # Streamlit WebSocket (requis pour le rechargement en temps réel)
    location ^~ /_stcore/stream {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app streamlit_efrei_data_science;
        set $upstream_port 8501;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port/_stcore/stream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Streamlit frontend — / → streamlit:8501
    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app streamlit_efrei_data_science;
        set $upstream_port 8501;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port/;
    }
}
